defaults: &defaults
  org_gdpr:
    UGent:
      - hanne.elsen@ugent.be
      - katya.vandriessche@uzgent.be
    AHS:
      - michael.meysman@arteveldehs.be

development: *defaults
production: *defaults
